/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import controle.ControleCurso;
import java.util.HashSet;
import javax.swing.JOptionPane;
import modelo.ModeloCurso;

/**
 *
 * @author Bruno
 */
public class Cadastrodecurso extends javax.swing.JFrame {
    
    ModeloCurso mod = new ModeloCurso();
    ControleCurso control = new ControleCurso();
    
    int flag = 0;
    int ID_CURSO = 0;
    /**
     * Creates new form Cadastrodecurso
     */
    public Cadastrodecurso() {
        
        initComponents();
        setLocationRelativeTo(null);
        jTextFieldId.setVisible(false);
        //jTextFieldId.setText("teste");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldTipoCurso = new javax.swing.JTextField();
        jTextFieldModalidade = new javax.swing.JTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHabilitacao = new javax.swing.JTextField();
        jTextFieldLocal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTurno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldVagasTurno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCargaHoraria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldRegimeLetivo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPeriodo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNommeCoordenador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldCPFCoordenador = new javax.swing.JTextField();
        jTextFieldTitulacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTempo = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dados do Curso");

        jTextFieldTipoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipoCursoActionPerformed(evt);
            }
        });

        jTextFieldModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModalidadeActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel1.setText("Modalidade:");

        jLabel2.setText("Tipo do Curso:");

        jLabel4.setText(" Curso:");

        jLabel5.setText("Habilitação: ");

        jTextFieldHabilitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHabilitacaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Local de Oferta:");

        jLabel6.setText("Turnos de Funcionamento:");

        jLabel8.setText("Numero de Vaga para cada Turno:");

        jLabel9.setText("Carga Horario do Curso:");

        jLabel10.setText("Horas");

        jLabel11.setText("Estrutura Curricular:");

        jLabel12.setText("Regime Letivo");

        jLabel13.setText("Períodos:");

        jLabel14.setText("Coordenador do Curso:");

        jLabel15.setText("Nome:");

        jLabel16.setText("CPF:");

        jLabel17.setText("Titulação:");

        jLabel18.setText("Tempo de Dedicação");

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCurso)
                                .addGap(273, 273, 273))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVagasTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel11))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldTipoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldModalidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldRegimeLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNommeCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCPFCoordenador))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTipoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldHabilitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldVagasTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRegimeLetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNommeCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldCPFCoordenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldTitulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModalidadeActionPerformed

    private void jTextFieldHabilitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHabilitacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHabilitacaoActionPerformed

    private void jTextFieldTipoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipoCursoActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Curso tela = new Curso();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        
        
        if (flag==1){
            mod.setTIPO_CURSO(jTextFieldTipoCurso.getText());
            mod.setMODALIDADE(jTextFieldModalidade.getText());
            mod.setCURSO(jTextFieldCurso.getText());
            mod.setHABILITACAO(jTextFieldHabilitacao.getText());
            mod.setLOCAL_OFERTA(jTextFieldLocal.getText());
            mod.setTURNO_FUNCIONAMENTO(jTextFieldTurno.getText());
            mod.setNUMERO_VAGAS(Integer.parseInt(jTextFieldVagasTurno.getText()));
            mod.setCARGA_HORARIA(Integer.parseInt(jTextFieldCargaHoraria.getText()));
            mod.setREGIME_LETIVO(jTextFieldRegimeLetivo.getText());
            mod.setPERIODOS(jTextFieldPeriodo.getText());
            mod.setNOME(jTextFieldNommeCoordenador.getText());
            mod.setCPF(jTextFieldCPFCoordenador.getText());
            mod.setTITULACAO(jTextFieldTitulacao.getText());
            mod.setTEMPO_DEDICACAO(jTextFieldTempo.getText());
            control.Salvar(mod);
        }else{
            mod.setID_CURSO(ID_CURSO);
            mod.setTIPO_CURSO(jTextFieldTipoCurso.getText());
            mod.setMODALIDADE(jTextFieldModalidade.getText());
            mod.setCURSO(jTextFieldCurso.getText());
            mod.setHABILITACAO(jTextFieldHabilitacao.getText());
            mod.setLOCAL_OFERTA(jTextFieldLocal.getText());
            mod.setTURNO_FUNCIONAMENTO(jTextFieldTurno.getText());
            mod.setNUMERO_VAGAS(Integer.parseInt(jTextFieldVagasTurno.getText()));
            mod.setCARGA_HORARIA(Integer.parseInt(jTextFieldCargaHoraria.getText()));
            mod.setREGIME_LETIVO(jTextFieldRegimeLetivo.getText());
            mod.setPERIODOS(jTextFieldPeriodo.getText());
            mod.setNOME(jTextFieldNommeCoordenador.getText());
            mod.setCPF(jTextFieldCPFCoordenador.getText());
            mod.setTITULACAO(jTextFieldTitulacao.getText());
            mod.setTEMPO_DEDICACAO(jTextFieldTempo.getText());
            control.Editar(mod);
        }
        
        jTextFieldTipoCurso.setEnabled(false);
        jTextFieldModalidade.setEnabled(false);
        jTextFieldCurso.setEnabled(false);
        jTextFieldHabilitacao.setEnabled(false);
        jTextFieldLocal.setEnabled(false);
        jTextFieldTurno.setEnabled(false);
        jTextFieldVagasTurno.setEnabled(false);
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldRegimeLetivo.setEnabled(false);
        jTextFieldPeriodo.setEnabled(false);
        jTextFieldNommeCoordenador.setEnabled(false);
        jTextFieldCPFCoordenador.setEnabled(false);
        jTextFieldTitulacao.setEnabled(false);
        jTextFieldTempo.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldTipoCurso.setText("");
        jTextFieldModalidade.setText("");
        jTextFieldCurso.setText("");
        jTextFieldHabilitacao.setText("");
        jTextFieldLocal.setText("");
        jTextFieldTurno.setText("");
        jTextFieldVagasTurno.setText("");
        jTextFieldCargaHoraria.setText("");
        jTextFieldRegimeLetivo.setText("");
        jTextFieldPeriodo.setText("");
        jTextFieldNommeCoordenador.setText("");
        jTextFieldCPFCoordenador.setText("");
        jTextFieldTitulacao.setText("");
        jTextFieldTempo.setText("");
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextFieldTipoCurso.setEnabled(true);
        jTextFieldModalidade.setEnabled(true);
        jTextFieldCurso.setEnabled(true);
        jTextFieldHabilitacao.setEnabled(true);
        jTextFieldLocal.setEnabled(true);
        jTextFieldTurno.setEnabled(true);
        jTextFieldVagasTurno.setEnabled(true);
        jTextFieldCargaHoraria.setEnabled(true);
        jTextFieldRegimeLetivo.setEnabled(true);
        jTextFieldPeriodo.setEnabled(true);
        jTextFieldNommeCoordenador.setEnabled(true);
        jTextFieldCPFCoordenador.setEnabled(true);
        jTextFieldTitulacao.setEnabled(true);
        jTextFieldTempo.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        
        //jTextFieldTipoCurso.setText(jTextFieldId.getText());
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrodecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrodecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrodecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrodecurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrodecurso().setVisible(true);
            }
        });
    }
    
    public void novo(){
        jButtonAlterar.setEnabled(false);
    }
    
    public void preenche(int ID){
        ID_CURSO = ID;
        ModeloCurso model = control.buscaCurso(mod, ID);
        jTextFieldCurso.setText(model.getCURSO());
        jTextFieldTipoCurso.setText(model.getTIPO_CURSO());
        jTextFieldModalidade.setText(model.getMODALIDADE());
        jTextFieldCurso.setText(model.getCURSO());
        jTextFieldHabilitacao.setText(model.getHABILITACAO());
        jTextFieldLocal.setText(model.getLOCAL_OFERTA());
        jTextFieldTurno.setText(model.getTURNO_FUNCIONAMENTO());
        jTextFieldVagasTurno.setText(Integer.toString(model.getNUMERO_VAGAS()));
        jTextFieldCargaHoraria.setText(Integer.toString(model.getCARGA_HORARIA()));
        jTextFieldRegimeLetivo.setText(model.getREGIME_LETIVO());
        jTextFieldPeriodo.setText(model.getPERIODOS());
        jTextFieldNommeCoordenador.setText(model.getNOME());
        jTextFieldCPFCoordenador.setText(model.getCPF());
        jTextFieldTitulacao.setText(model.getTITULACAO());
        jTextFieldTempo.setText(model.getTEMPO_DEDICACAO());
        jTextFieldTipoCurso.setEnabled(false);
        jTextFieldModalidade.setEnabled(false);
        jTextFieldCurso.setEnabled(false);
        jTextFieldHabilitacao.setEnabled(false);
        jTextFieldLocal.setEnabled(false);
        jTextFieldTurno.setEnabled(false);
        jTextFieldVagasTurno.setEnabled(false);
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldRegimeLetivo.setEnabled(false);
        jTextFieldPeriodo.setEnabled(false);
        jTextFieldNommeCoordenador.setEnabled(false);
        jTextFieldCPFCoordenador.setEnabled(false);
        jTextFieldTitulacao.setEnabled(false);
        jTextFieldTempo.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldCPFCoordenador;
    private javax.swing.JTextField jTextFieldCargaHoraria;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldHabilitacao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLocal;
    private javax.swing.JTextField jTextFieldModalidade;
    private javax.swing.JTextField jTextFieldNommeCoordenador;
    private javax.swing.JTextField jTextFieldPeriodo;
    private javax.swing.JTextField jTextFieldRegimeLetivo;
    private javax.swing.JTextField jTextFieldTempo;
    private javax.swing.JTextField jTextFieldTipoCurso;
    private javax.swing.JTextField jTextFieldTitulacao;
    private javax.swing.JTextField jTextFieldTurno;
    private javax.swing.JTextField jTextFieldVagasTurno;
    // End of variables declaration//GEN-END:variables
}
