/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import controle.ControlePlanoEnsino;
import controle.conectaBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ModeloPlanoEnsino;

/**
 *
 * @author Diarley Gomes
 */
public class PlanoEnsino extends javax.swing.JFrame {
    conectaBD conex = new conectaBD();
    ModeloPlanoEnsino mod = new ModeloPlanoEnsino();
    ControlePlanoEnsino control = new ControlePlanoEnsino();
    
    /**
     * Creates new form PlanoEnsino
     */
    public PlanoEnsino() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonBuscarDisciplina = new javax.swing.JButton();
        jLabelDisciplina = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCargaHoraria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPeriodo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMatriculaProf = new javax.swing.JTextField();
        jButtonBuscarProfessor = new javax.swing.JButton();
        jLabelProfessor = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEmenta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCompetencia = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaMetodologia = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaAvaliacao = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextAreaBibliografia = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaCronograma = new javax.swing.JTextArea();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plano de Ensino");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("IDENTIFICAÇÃO");

        jLabel2.setText("Código da Disciplina:");

        jButtonBuscarDisciplina.setText("Buscar");
        jButtonBuscarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDisciplinaActionPerformed(evt);
            }
        });

        jLabelDisciplina.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Carga Horária:");

        jTextFieldCargaHoraria.setEnabled(false);

        jLabel4.setText("horas");

        jLabel5.setText("Período do Curso:");

        jTextFieldPeriodo.setEnabled(false);

        jLabel6.setText("Matrícula Professor (a):");

        jTextFieldMatriculaProf.setEnabled(false);
        jTextFieldMatriculaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaProfActionPerformed(evt);
            }
        });

        jButtonBuscarProfessor.setText("Buscar");
        jButtonBuscarProfessor.setEnabled(false);
        jButtonBuscarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProfessorActionPerformed(evt);
            }
        });

        jLabelProfessor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("EMENTA");

        jTextAreaEmenta.setColumns(20);
        jTextAreaEmenta.setRows(5);
        jTextAreaEmenta.setText("Descrever a ementa do curso.");
        jTextAreaEmenta.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaEmenta);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("COMPETÊNCIAS E HABILIDADES");

        jTextAreaCompetencia.setColumns(20);
        jTextAreaCompetencia.setRows(5);
        jTextAreaCompetencia.setText("Descrever as competências e habilidades a serem adquiridas com o curso.");
        jTextAreaCompetencia.setEnabled(false);
        jScrollPane2.setViewportView(jTextAreaCompetencia);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("METODOLOGIA DE ENSINO");

        jTextAreaMetodologia.setColumns(20);
        jTextAreaMetodologia.setRows(5);
        jTextAreaMetodologia.setText("Descrever as técnicas e recursos da metodologia.");
        jTextAreaMetodologia.setEnabled(false);
        jScrollPane3.setViewportView(jTextAreaMetodologia);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CRONOGRAMA DE ATIVIDADES");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("AVALIAÇÃO");

        jTextAreaAvaliacao.setColumns(20);
        jTextAreaAvaliacao.setRows(5);
        jTextAreaAvaliacao.setText("Critérios de avaliação.");
        jTextAreaAvaliacao.setEnabled(false);
        jScrollPane6.setViewportView(jTextAreaAvaliacao);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("BIBLIOGRAFIA");

        jTextAreaBibliografia.setColumns(20);
        jTextAreaBibliografia.setRows(5);
        jTextAreaBibliografia.setText("Incluir a bibliografia básica e complementar.");
        jTextAreaBibliografia.setEnabled(false);
        jScrollPane7.setViewportView(jTextAreaBibliografia);

        jTextAreaCronograma.setColumns(20);
        jTextAreaCronograma.setRows(5);
        jTextAreaCronograma.setText("Descrever o cronograma de atividades.");
        jTextAreaCronograma.setEnabled(false);
        jScrollPane4.setViewportView(jTextAreaCronograma);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel12)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(96, 96, 96)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldMatriculaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonBuscarProfessor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonBuscarDisciplina)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(207, 207, 207)
                            .addComponent(jLabel8))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(jLabel7))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(232, 232, 232)
                            .addComponent(jLabel9))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(213, 213, 213)
                            .addComponent(jLabel10))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscarDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldMatriculaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBuscarProfessor))
                    .addComponent(jLabelProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDisciplinaActionPerformed
        String codigo = jTextFieldCodigo.getText();
        ModeloPlanoEnsino model = control.buscaPlano(mod, codigo);
        
        jTextFieldCodigo.setText(model.getCODIGO_DISCIPLINA());
        jLabelDisciplina.setText(model.getNOME_DISCIPLINA());
        jTextFieldCargaHoraria.setText(String.valueOf(model.getCARGA_HORARIA()));
        jTextFieldPeriodo.setText(model.getPERIODO_DO_CURSO());
        jTextFieldMatriculaProf.setText(model.getMATRICULA_PROFESSOR());
        jLabelProfessor.setText(model.getNOME_PROFESSOR());
        jTextAreaEmenta.setText(model.getEMENTA());
        jTextAreaCompetencia.setText(model.getCOMPETENCIAS_E_HABILIDADES());
        jTextAreaMetodologia.setText(model.getMETODOLOGIA_DE_ENSINO());
        jTextAreaCronograma.setText(model.getCRONOGRAMA_DE_ATIVIDADES());
        jTextAreaAvaliacao.setText(model.getAVALIACAO());
        jTextAreaBibliografia.setText(model.getBIBLIOGRAFIA());
        
        
    }//GEN-LAST:event_jButtonBuscarDisciplinaActionPerformed

    private void jButtonBuscarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProfessorActionPerformed
        String matricula = jTextFieldMatriculaProf.getText();
        conex.conexao();
        conex.executaSql("SELECT * FROM Professor WHERE MATRICULA LIKE '%" + matricula + "%';");
        
        try {
            conex.rs.first();
            mod.setID_PROFESSOR(conex.rs.getInt("ID_PROFESSOR"));
            mod.setNOME_PROFESSOR(conex.rs.getString("PROFESSOR"));
            mod.setMATRICULA_PROFESSOR(conex.rs.getString("MATRICULA"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Professor não encontrado!");
        }
        conex.desconecta();
        jTextFieldMatriculaProf.setText(mod.getMATRICULA_PROFESSOR());
        jLabelProfessor.setText(mod.getNOME_PROFESSOR());
        
    }//GEN-LAST:event_jButtonBuscarProfessorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Principal tela = new Principal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldMatriculaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaProfActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jTextFieldCargaHoraria.setEnabled(true);
        jTextFieldPeriodo.setEnabled(true);
        jTextFieldMatriculaProf.setEnabled(true);
        jLabelProfessor.setEnabled(true);
        jTextAreaEmenta.setEnabled(true);
        jTextAreaCompetencia.setEnabled(true);
        jTextAreaMetodologia.setEnabled(true);
        jTextAreaCronograma.setEnabled(true);
        jTextAreaAvaliacao.setEnabled(true);
        jTextAreaBibliografia.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonBuscarProfessor.setEnabled(true);
        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldPeriodo.setEnabled(false);
        jTextFieldMatriculaProf.setEnabled(false);
        jLabelProfessor.setEnabled(false);
        jTextAreaEmenta.setEnabled(false);
        jTextAreaCompetencia.setEnabled(false);
        jTextAreaMetodologia.setEnabled(false);
        jTextAreaCronograma.setEnabled(false);
        jTextAreaAvaliacao.setEnabled(false);
        jTextAreaBibliografia.setEnabled(false);
        jButtonAlterar.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonAlterar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonBuscarProfessor.setEnabled(false);
        
        jTextFieldCodigo.setText("");
        jLabelDisciplina.setText("");
        jTextFieldCargaHoraria.setText(String.valueOf(""));
        jTextFieldPeriodo.setText("");
        jTextFieldMatriculaProf.setText("");
        jLabelProfessor.setText("");
        jTextAreaEmenta.setText("Descrever a ementa do curso.");
        jTextAreaCompetencia.setText("Descrever as competências e habilidades a serem adquiridas com o curso.");
        jTextAreaMetodologia.setText("Descrever as técnicas e recursos da metodologia.");
        jTextAreaCronograma.setText("Descrever o cronograma de atividades.");
        jTextAreaAvaliacao.setText("Critérios de avaliação.");
        jTextAreaBibliografia.setText("Incluir a bibliografia básica e complementar.");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String codigo = jTextFieldCodigo.getText();
        ModeloPlanoEnsino model = control.buscaPlano(mod, codigo);
        
        if (model.getID_PLANO_ENSINO() == 0){
            mod.setCARGA_HORARIA(Integer.parseInt(jTextFieldCargaHoraria.getText()));
            mod.setPERIODO_DO_CURSO(jTextFieldPeriodo.getText());
            mod.setEMENTA(jTextAreaEmenta.getText());
            mod.setCOMPETENCIAS_E_HABILIDADES(jTextAreaCompetencia.getText());
            mod.setMETODOLOGIA_DE_ENSINO(jTextAreaMetodologia.getText());
            mod.setCRONOGRAMA_DE_ATIVIDADES(jTextAreaCronograma.getText());
            mod.setAVALIACAO(jTextAreaAvaliacao.getText());
            mod.setBIBLIOGRAFIA(jTextAreaBibliografia.getText());
            
            if(jLabelProfessor.equals("")){
                mod.setID_PROFESSOR(0);
            }
            
            control.Salvar(mod);
        }else{
            mod.setCARGA_HORARIA(Integer.parseInt(jTextFieldCargaHoraria.getText()));
            mod.setPERIODO_DO_CURSO(jTextFieldPeriodo.getText());
            mod.setEMENTA(jTextAreaEmenta.getText());
            mod.setCOMPETENCIAS_E_HABILIDADES(jTextAreaCompetencia.getText());
            mod.setMETODOLOGIA_DE_ENSINO(jTextAreaMetodologia.getText());
            mod.setCRONOGRAMA_DE_ATIVIDADES(jTextAreaCronograma.getText());
            mod.setAVALIACAO(jTextAreaAvaliacao.getText());
            mod.setBIBLIOGRAFIA(jTextAreaBibliografia.getText());
            
            if(jLabelProfessor.equals("")){
                mod.setID_PROFESSOR(0);
            }
            
            control.Editar(mod);
        }
        
        jTextFieldCargaHoraria.setEnabled(false);
        jTextFieldPeriodo.setEnabled(false);
        jTextFieldMatriculaProf.setEnabled(false);
        jLabelProfessor.setEnabled(false);
        jTextAreaEmenta.setEnabled(false);
        jTextAreaCompetencia.setEnabled(false);
        jTextAreaMetodologia.setEnabled(false);
        jTextAreaCronograma.setEnabled(false);
        jTextAreaAvaliacao.setEnabled(false);
        jTextAreaBibliografia.setEnabled(false);
        jButtonAlterar.setEnabled(true);
        jButtonCancelar.setEnabled(false);
        jButtonAlterar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonBuscarProfessor.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanoEnsino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanoEnsino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanoEnsino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanoEnsino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanoEnsino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscarDisciplina;
    private javax.swing.JButton jButtonBuscarProfessor;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDisciplina;
    private javax.swing.JLabel jLabelProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextAreaAvaliacao;
    private javax.swing.JTextArea jTextAreaBibliografia;
    private javax.swing.JTextArea jTextAreaCompetencia;
    private javax.swing.JTextArea jTextAreaCronograma;
    private javax.swing.JTextArea jTextAreaEmenta;
    private javax.swing.JTextArea jTextAreaMetodologia;
    private javax.swing.JTextField jTextFieldCargaHoraria;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldMatriculaProf;
    private javax.swing.JTextField jTextFieldPeriodo;
    // End of variables declaration//GEN-END:variables
}
