/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import controle.ControlePPC;
import controle.conectaBD;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.ModeloPPC;



/**
 *
 * @author Bruno
 */
public class PPC extends javax.swing.JFrame {
    ModeloPPC mod = new ModeloPPC();
    ControlePPC control = new ControlePPC();
    conectaBD conex = new conectaBD();
    
    /**
     * Creates new form PPC
     */
    public PPC() {
        initComponents();
        setLocationRelativeTo(null);
        preencheCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPerfilCurso = new javax.swing.JTextField();
        jTextFieldAcessoCurso = new javax.swing.JTextField();
        jTextFieldSistemaEnsinoAprendizagem = new javax.swing.JTextField();
        jTextFieldTCC = new javax.swing.JTextField();
        jTextFieldPoliticaPCD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEstagioCurricular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldRepreGrafica = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSistemaAvaliacao = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jComboBoxPPC = new javax.swing.JComboBox();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Pedagogico de Curso");

        jLabel2.setText("Cursos");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel3.setText("Perfil Cursos");

        jLabel4.setText("Forma de Acesso Cursos");

        jLabel5.setText("Sistema de Avaliação do Processo Ensino Aprendizagem");

        jLabel6.setText("Trabalho de Conclusão de Curso");

        jLabel7.setText("Política de Atendimento a Pessoa Com Deficiência");

        jTextFieldPerfilCurso.setEnabled(false);

        jTextFieldAcessoCurso.setEnabled(false);
        jTextFieldAcessoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAcessoCursoActionPerformed(evt);
            }
        });

        jTextFieldSistemaEnsinoAprendizagem.setEnabled(false);

        jTextFieldTCC.setEnabled(false);

        jTextFieldPoliticaPCD.setEnabled(false);

        jLabel8.setText("Estágio Curricular");

        jTextFieldEstagioCurricular.setEnabled(false);

        jLabel11.setText("Representação Grafica");

        jTextFieldRepreGrafica.setEnabled(false);
        jTextFieldRepreGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepreGraficaActionPerformed(evt);
            }
        });

        jLabel12.setText("Sistema de Avaliação");

        jTextFieldSistemaAvaliacao.setEnabled(false);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jComboBoxPPC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Curso..." }));
        jComboBoxPPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPPCActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPoliticaPCD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextFieldTCC))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldEstagioCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldPerfilCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSistemaEnsinoAprendizagem))
                                    .addComponent(jTextFieldAcessoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldRepreGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSistemaAvaliacao)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAlterar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxPPC, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscar)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPerfilCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRepreGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAcessoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSistemaAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addComponent(jTextFieldSistemaEnsinoAprendizagem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEstagioCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPoliticaPCD, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencheCurso(){
        conex.conexao();
        conex.executaSql("SELECT CURSO FROM Cursos ORDER BY CURSO;");
        try {
            conex.rs.first();
            //jComboBoxPPC.removeAllItems();
            //jComboBoxPPC.addItem("Selecione o Curso...");
            do{
                jComboBoxPPC.addItem(conex.rs.getString("CURSO"));
            }while(conex.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher cursos "+ex);
        }
        conex.desconecta();
    }
    
    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        Principal tela = new Principal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String caixa = (String) jComboBoxPPC.getSelectedItem();
        
        if(caixa.equals("Selecione o Curso...")){
        }else{
            //JOptionPane.showMessageDialog(null, "aqui");
            mod.setPERFIL_CURSO(jTextFieldPerfilCurso.getText());
            mod.setREPRESENTACAO_GRAFICA(jTextFieldRepreGrafica.getText());
            mod.setFORMA_DE_ACESSO_CURSO(jTextFieldAcessoCurso.getText());
            mod.setSISTEMA_DE_AVALIACAO(jTextFieldSistemaAvaliacao.getText());
            mod.setSISTEMA_DE_AVALIACAO_DO_PROCESSO_ENSINO_APRENDIZAGEM(jTextFieldSistemaEnsinoAprendizagem.getText());
            mod.setTRABALHO_DE_CONCLUSAO_DE_CURSO(jTextFieldTCC.getText());
            mod.setESTAGIO_CURRICULAR(jTextFieldEstagioCurricular.getText());
            mod.setPOLITICA_DE_ATENDIMENTO_A_PESSOA_COM_DEFICIENCIA(jTextFieldPoliticaPCD.getText());
            control.Salvar(mod, caixa);

            jTextFieldPerfilCurso.setEnabled(false);
            jTextFieldRepreGrafica.setEnabled(false);
            jTextFieldAcessoCurso.setEnabled(false);
            jTextFieldSistemaAvaliacao.setEnabled(false);
            jTextFieldSistemaEnsinoAprendizagem.setEnabled(false);
            jTextFieldTCC.setEnabled(false);
            jTextFieldEstagioCurricular.setEnabled(false);
            jTextFieldPoliticaPCD.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonVoltar.setEnabled(true);
            jButtonAlterar.setEnabled(true);
            jComboBoxPPC.setEnabled(true);
            jButtonBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        jTextFieldPerfilCurso.setEnabled(true);
        jTextFieldRepreGrafica.setEnabled(true);
        jTextFieldAcessoCurso.setEnabled(true);
        jTextFieldSistemaAvaliacao.setEnabled(true);
        jTextFieldSistemaEnsinoAprendizagem.setEnabled(true);
        jTextFieldTCC.setEnabled(true);
        jTextFieldEstagioCurricular.setEnabled(true);
        jTextFieldPoliticaPCD.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonVoltar.setEnabled(false);
        jComboBoxPPC.setEnabled(false);
        jButtonBuscar.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        String caixa = (String) jComboBoxPPC.getSelectedItem();
        
        if(caixa.equals("Selecione o Curso...")){
        }else{
            ModeloPPC model = control.buscaPPC(mod, caixa);
            jTextFieldPerfilCurso.setText(model.getPERFIL_CURSO());
            jTextFieldRepreGrafica.setText(model.getREPRESENTACAO_GRAFICA());
            jTextFieldAcessoCurso.setText(model.getFORMA_DE_ACESSO_CURSO());
            jTextFieldSistemaAvaliacao.setText(model.getSISTEMA_DE_AVALIACAO());
            jTextFieldSistemaEnsinoAprendizagem.setText(model.getSISTEMA_DE_AVALIACAO_DO_PROCESSO_ENSINO_APRENDIZAGEM());
            jTextFieldTCC.setText(model.getTRABALHO_DE_CONCLUSAO_DE_CURSO());
            jTextFieldEstagioCurricular.setText(model.getESTAGIO_CURRICULAR());
            jTextFieldPoliticaPCD.setText(model.getPOLITICA_DE_ATENDIMENTO_A_PESSOA_COM_DEFICIENCIA());

            jTextFieldPerfilCurso.setEnabled(false);
            jTextFieldRepreGrafica.setEnabled(false);
            jTextFieldAcessoCurso.setEnabled(false);
            jTextFieldSistemaAvaliacao.setEnabled(false);
            jTextFieldSistemaEnsinoAprendizagem.setEnabled(false);
            jTextFieldTCC.setEnabled(false);
            jTextFieldEstagioCurricular.setEnabled(false);
            jTextFieldPoliticaPCD.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonAlterar.setEnabled(true);
            jButtonVoltar.setEnabled(true);
            jComboBoxPPC.setEnabled(true);
            jButtonBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed
    
    private void jTextFieldRepreGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepreGraficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRepreGraficaActionPerformed

    private void jTextFieldAcessoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAcessoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAcessoCursoActionPerformed

    private void jComboBoxPPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPPCActionPerformed
        
    }//GEN-LAST:event_jComboBoxPPCActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String caixa = (String) jComboBoxPPC.getSelectedItem();
        
        if(caixa.equals("Selecione o Curso...")){
        }else{
            ModeloPPC model = control.buscaPPC(mod, caixa);
            jTextFieldPerfilCurso.setText(model.getPERFIL_CURSO());
            jTextFieldRepreGrafica.setText(model.getREPRESENTACAO_GRAFICA());
            jTextFieldAcessoCurso.setText(model.getFORMA_DE_ACESSO_CURSO());
            jTextFieldSistemaAvaliacao.setText(model.getSISTEMA_DE_AVALIACAO());
            jTextFieldSistemaEnsinoAprendizagem.setText(model.getSISTEMA_DE_AVALIACAO_DO_PROCESSO_ENSINO_APRENDIZAGEM());
            jTextFieldTCC.setText(model.getTRABALHO_DE_CONCLUSAO_DE_CURSO());
            jTextFieldEstagioCurricular.setText(model.getESTAGIO_CURRICULAR());
            jTextFieldPoliticaPCD.setText(model.getPOLITICA_DE_ATENDIMENTO_A_PESSOA_COM_DEFICIENCIA());

            jTextFieldPerfilCurso.setEnabled(false);
            jTextFieldRepreGrafica.setEnabled(false);
            jTextFieldAcessoCurso.setEnabled(false);
            jTextFieldSistemaAvaliacao.setEnabled(false);
            jTextFieldSistemaEnsinoAprendizagem.setEnabled(false);
            jTextFieldTCC.setEnabled(false);
            jTextFieldEstagioCurricular.setEnabled(false);
            jTextFieldPoliticaPCD.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonAlterar.setEnabled(true);
            jButtonVoltar.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxPPC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextFieldAcessoCurso;
    private javax.swing.JTextField jTextFieldEstagioCurricular;
    private javax.swing.JTextField jTextFieldPerfilCurso;
    private javax.swing.JTextField jTextFieldPoliticaPCD;
    private javax.swing.JTextField jTextFieldRepreGrafica;
    private javax.swing.JTextField jTextFieldSistemaAvaliacao;
    private javax.swing.JTextField jTextFieldSistemaEnsinoAprendizagem;
    private javax.swing.JTextField jTextFieldTCC;
    // End of variables declaration//GEN-END:variables
}
